"""init db

Revision ID: 5cfdf3160faf
Revises: 
Create Date: 2020-10-06 17:24:10.375750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfdf3160faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UPC', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('album_id', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('album_name', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('album_cover_image', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('album_release_date', sa.String(length=8, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('album_type', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('album_distributor', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('album_running_time', sa.String(length=15, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('album_track_num', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('album_category', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('artist_name', sa.String(length=30, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('artist_id', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('artist_image', sa.String(length=250, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('title_track_name', sa.String(length=128, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('creator_code', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('creator_name', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('trust_date', sa.String(length=10, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('trust_end_date', sa.String(length=10, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('MIS_code', sa.String(length=250, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_by', sa.String(length=15, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=15, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('blacklist_tokens')
    op.drop_table('album')
    # ### end Alembic commands ###
